This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by server configure 0.2, which was
generated by GNU Autoconf 2.60.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = mephisto
uname -m = i386
uname -r = 6.0-RELEASE
uname -s = FreeBSD
uname -v = FreeBSD 6.0-RELEASE #0: Fri Jun  2 15:44:24 JST 2006     s-okubo@mephisto:/usr/obj/usr/src/sys/MEPHISTO 

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/bin
PATH: /usr/local/bin/mh
PATH: /usr/bin/X11
PATH: /usr/local/gnu/gnome2/bin
PATH: /usr/hosts
PATH: /usr/bin
PATH: /bin
PATH: /usr/ccs/bin
PATH: /usr/5bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/ucb
PATH: /usr/etc
PATH: /home/tnlab/s-okubo/bin
PATH: /opt/X11R6.3/bin
PATH: /usr/openwin/bin
PATH: /usr/local2/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:1769: checking for a BSD-compatible install
configure:1825: result: /usr/local/bin/ginstall -c
configure:1836: checking whether build environment is sane
configure:1879: result: yes
configure:1944: checking for gawk
configure:1974: result: no
configure:1944: checking for mawk
configure:1974: result: no
configure:1944: checking for nawk
configure:1960: found /usr/bin/nawk
configure:1971: result: nawk
configure:1982: checking whether make sets $(MAKE)
configure:2003: result: yes
configure:2230: checking for gcc
configure:2246: found /usr/bin/gcc
configure:2257: result: gcc
configure:2495: checking for C compiler version
configure:2502: gcc --version >&5
gcc (GCC) 3.4.4 [FreeBSD] 20050518
Copyright (C) 2004 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2505: $? = 0
configure:2512: gcc -v >&5
Using built-in specs.
Configured with: FreeBSD/i386 system compiler
Thread model: posix
gcc version 3.4.4 [FreeBSD] 20050518
configure:2515: $? = 0
configure:2522: gcc -V >&5
gcc: `-V' option must have argument
configure:2525: $? = 1
configure:2548: checking for C compiler default output file name
configure:2575: gcc    conftest.c  >&5
configure:2578: $? = 0
configure:2624: result: a.out
configure:2629: checking whether the C compiler works
configure:2639: ./a.out
configure:2642: $? = 0
configure:2659: result: yes
configure:2666: checking whether we are cross compiling
configure:2668: result: no
configure:2671: checking for suffix of executables
configure:2678: gcc -o conftest    conftest.c  >&5
configure:2681: $? = 0
configure:2705: result: 
configure:2711: checking for suffix of object files
configure:2737: gcc -c   conftest.c >&5
configure:2740: $? = 0
configure:2763: result: o
configure:2767: checking whether we are using the GNU C compiler
configure:2796: gcc -c   conftest.c >&5
configure:2802: $? = 0
configure:2809: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:2812: $? = 0
configure:2819: test -s conftest.o
configure:2822: $? = 0
configure:2836: result: yes
configure:2841: checking whether gcc accepts -g
configure:2871: gcc -c -g  conftest.c >&5
configure:2877: $? = 0
configure:2884: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:2887: $? = 0
configure:2894: test -s conftest.o
configure:2897: $? = 0
configure:3027: result: yes
configure:3044: checking for gcc option to accept ISO C89
configure:3118: gcc  -c -g -O2  conftest.c >&5
configure:3124: $? = 0
configure:3131: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:3134: $? = 0
configure:3141: test -s conftest.o
configure:3144: $? = 0
configure:3164: result: none needed
configure:3193: checking for style of include used by make
configure:3221: result: GNU
configure:3249: checking dependency style of gcc
configure:3339: result: gcc3
configure:3363: checking how to run the C preprocessor
configure:3403: gcc -E  conftest.c
configure:3409: $? = 0
configure:3447: gcc -E  conftest.c
conftest.c:8:28: ac_nonexistent.h: No such file or directory
configure:3453: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "server"
| #define PACKAGE_TARNAME "server"
| #define PACKAGE_VERSION "0.2"
| #define PACKAGE_STRING "server 0.2"
| #define PACKAGE_BUGREPORT "tnlab-webmaster@ice.uec.ac.jp"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:3493: result: gcc -E
configure:3522: gcc -E  conftest.c
configure:3528: $? = 0
configure:3566: gcc -E  conftest.c
conftest.c:8:28: ac_nonexistent.h: No such file or directory
configure:3572: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "server"
| #define PACKAGE_TARNAME "server"
| #define PACKAGE_VERSION "0.2"
| #define PACKAGE_STRING "server 0.2"
| #define PACKAGE_BUGREPORT "tnlab-webmaster@ice.uec.ac.jp"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:3617: checking for X
configure:3875: result: libraries /usr/X11R6/lib, headers /usr/X11R6/include
configure:4078: gcc -o conftest -g -O2   conftest.c   -L/usr/X11R6/lib -lX11 >&5
configure:4084: $? = 0
configure:4091: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:4094: $? = 0
configure:4101: test -s conftest
configure:4104: $? = 0
configure:4289: checking for gethostbyname
configure:4345: gcc -o conftest -g -O2   conftest.c  >&5
configure:4351: $? = 0
configure:4358: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:4361: $? = 0
configure:4368: test -s conftest
configure:4371: $? = 0
configure:4384: result: yes
configure:4561: checking for connect
configure:4617: gcc -o conftest -g -O2   conftest.c  >&5
configure:4623: $? = 0
configure:4630: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:4633: $? = 0
configure:4640: test -s conftest
configure:4643: $? = 0
configure:4656: result: yes
configure:4744: checking for remove
configure:4800: gcc -o conftest -g -O2   conftest.c  >&5
configure:4806: $? = 0
configure:4813: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:4816: $? = 0
configure:4823: test -s conftest
configure:4826: $? = 0
configure:4839: result: yes
configure:4927: checking for shmat
configure:4983: gcc -o conftest -g -O2   conftest.c  >&5
configure:4989: $? = 0
configure:4996: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:4999: $? = 0
configure:5006: test -s conftest
configure:5009: $? = 0
configure:5022: result: yes
configure:5119: checking for IceConnectionNumber in -lICE
configure:5154: gcc -o conftest -g -O2   -L/usr/X11R6/lib conftest.c -lICE   >&5
configure:5160: $? = 0
configure:5167: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:5170: $? = 0
configure:5177: test -s conftest
configure:5180: $? = 0
configure:5194: result: yes
configure:5208: checking for library containing gethostbyname
configure:5249: gcc -o conftest -g -O2   conftest.c  >&5
configure:5255: $? = 0
configure:5262: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:5265: $? = 0
configure:5272: test -s conftest
configure:5275: $? = 0
configure:5299: result: none required
configure:5307: checking for library containing socket
configure:5348: gcc -o conftest -g -O2   conftest.c  >&5
configure:5354: $? = 0
configure:5361: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:5364: $? = 0
configure:5371: test -s conftest
configure:5374: $? = 0
configure:5398: result: none required
configure:5492: checking for main in -lXpm
configure:5521: gcc -o conftest -g -O2   conftest.c -lXpm   >&5
/usr/bin/ld: cannot find -lXpm
configure:5527: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "server"
| #define PACKAGE_TARNAME "server"
| #define PACKAGE_VERSION "0.2"
| #define PACKAGE_STRING "server 0.2"
| #define PACKAGE_BUGREPORT "tnlab-webmaster@ice.uec.ac.jp"
| /* end confdefs.h.  */
| 
| 
| int
| main ()
| {
| return main ();
|   ;
|   return 0;
| }
configure:5561: result: no
configure:5573: checking for main in -lX11
configure:5602: gcc -o conftest -g -O2   conftest.c -lX11   >&5
/usr/bin/ld: cannot find -lX11
configure:5608: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "server"
| #define PACKAGE_TARNAME "server"
| #define PACKAGE_VERSION "0.2"
| #define PACKAGE_STRING "server 0.2"
| #define PACKAGE_BUGREPORT "tnlab-webmaster@ice.uec.ac.jp"
| /* end confdefs.h.  */
| 
| 
| int
| main ()
| {
| return main ();
|   ;
|   return 0;
| }
configure:5642: result: no
configure:5654: checking for main in -lXt
configure:5683: gcc -o conftest -g -O2   conftest.c -lXt   >&5
/usr/bin/ld: cannot find -lXt
configure:5689: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "server"
| #define PACKAGE_TARNAME "server"
| #define PACKAGE_VERSION "0.2"
| #define PACKAGE_STRING "server 0.2"
| #define PACKAGE_BUGREPORT "tnlab-webmaster@ice.uec.ac.jp"
| /* end confdefs.h.  */
| 
| 
| int
| main ()
| {
| return main ();
|   ;
|   return 0;
| }
configure:5723: result: no
configure:5735: checking for main in -lXaw
configure:5764: gcc -o conftest -g -O2   conftest.c -lXaw   >&5
/usr/bin/ld: cannot find -lXaw
configure:5770: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME "server"
| #define PACKAGE_TARNAME "server"
| #define PACKAGE_VERSION "0.2"
| #define PACKAGE_STRING "server 0.2"
| #define PACKAGE_BUGREPORT "tnlab-webmaster@ice.uec.ac.jp"
| /* end confdefs.h.  */
| 
| 
| int
| main ()
| {
| return main ();
|   ;
|   return 0;
| }
configure:5804: result: no
configure:5819: checking for grep that handles long lines and -e
configure:5893: result: /usr/bin/grep
configure:5898: checking for egrep
configure:5976: result: /usr/bin/grep -E
configure:5981: checking for ANSI C header files
configure:6011: gcc -c -g -O2  conftest.c >&5
configure:6017: $? = 0
configure:6024: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6027: $? = 0
configure:6034: test -s conftest.o
configure:6037: $? = 0
configure:6133: gcc -o conftest -g -O2   conftest.c  >&5
configure:6136: $? = 0
configure:6142: ./conftest
configure:6145: $? = 0
configure:6162: result: yes
configure:6186: checking for sys/types.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for sys/stat.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for stdlib.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for string.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for memory.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for strings.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for inttypes.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for stdint.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6186: checking for unistd.h
configure:6207: gcc -c -g -O2  conftest.c >&5
configure:6213: $? = 0
configure:6220: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6223: $? = 0
configure:6230: test -s conftest.o
configure:6233: $? = 0
configure:6246: result: yes
configure:6278: checking arpa/inet.h usability
configure:6295: gcc -c -g -O2  conftest.c >&5
configure:6301: $? = 0
configure:6308: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6311: $? = 0
configure:6318: test -s conftest.o
configure:6321: $? = 0
configure:6332: result: yes
configure:6336: checking arpa/inet.h presence
configure:6351: gcc -E  conftest.c
configure:6357: $? = 0
configure:6378: result: yes
configure:6411: checking for arpa/inet.h
configure:6419: result: yes
configure:6268: checking for stdlib.h
configure:6274: result: yes
configure:6268: checking for string.h
configure:6274: result: yes
configure:6268: checking for strings.h
configure:6274: result: yes
configure:6278: checking sys/socket.h usability
configure:6295: gcc -c -g -O2  conftest.c >&5
configure:6301: $? = 0
configure:6308: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6311: $? = 0
configure:6318: test -s conftest.o
configure:6321: $? = 0
configure:6332: result: yes
configure:6336: checking sys/socket.h presence
configure:6351: gcc -E  conftest.c
configure:6357: $? = 0
configure:6378: result: yes
configure:6411: checking for sys/socket.h
configure:6419: result: yes
configure:6268: checking for unistd.h
configure:6274: result: yes
configure:6443: checking for bzero
configure:6499: gcc -o conftest -g -O2   conftest.c  >&5
conftest.c:47: warning: conflicting types for built-in function 'bzero'
configure:6505: $? = 0
configure:6512: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6515: $? = 0
configure:6522: test -s conftest
configure:6525: $? = 0
configure:6539: result: yes
configure:6443: checking for inet_ntoa
configure:6499: gcc -o conftest -g -O2   conftest.c  >&5
configure:6505: $? = 0
configure:6512: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6515: $? = 0
configure:6522: test -s conftest
configure:6525: $? = 0
configure:6539: result: yes
configure:6443: checking for memset
configure:6499: gcc -o conftest -g -O2   conftest.c  >&5
conftest.c:49: warning: conflicting types for built-in function 'memset'
configure:6505: $? = 0
configure:6512: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6515: $? = 0
configure:6522: test -s conftest
configure:6525: $? = 0
configure:6539: result: yes
configure:6443: checking for socket
configure:6499: gcc -o conftest -g -O2   conftest.c  >&5
configure:6505: $? = 0
configure:6512: test -z "$ac_c_werror_flag" || test ! -s conftest.err
configure:6515: $? = 0
configure:6522: test -s conftest
configure:6525: $? = 0
configure:6539: result: yes
configure:6666: creating ./config.status

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by server config.status 0.2, which was
generated by GNU Autoconf 2.60.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ./config.status 

on mephisto

config.status:626: creating Makefile
config.status:626: creating src/Makefile
config.status:626: creating src/config.h
config.status:900: executing depfiles commands

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_c_compiler_gnu=yes
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_XMKMF_set=
ac_cv_env_XMKMF_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_func_bzero=yes
ac_cv_func_connect=yes
ac_cv_func_gethostbyname=yes
ac_cv_func_inet_ntoa=yes
ac_cv_func_memset=yes
ac_cv_func_remove=yes
ac_cv_func_shmat=yes
ac_cv_func_socket=yes
ac_cv_have_x='have_x=yes	ac_x_includes='\''/usr/X11R6/include'\''	ac_x_libraries='\''/usr/X11R6/lib'\'''
ac_cv_header_arpa_inet_h=yes
ac_cv_header_inttypes_h=yes
ac_cv_header_memory_h=yes
ac_cv_header_stdc=yes
ac_cv_header_stdint_h=yes
ac_cv_header_stdlib_h=yes
ac_cv_header_string_h=yes
ac_cv_header_strings_h=yes
ac_cv_header_sys_socket_h=yes
ac_cv_header_sys_stat_h=yes
ac_cv_header_sys_types_h=yes
ac_cv_header_unistd_h=yes
ac_cv_lib_ICE_IceConnectionNumber=yes
ac_cv_lib_X11_main=no
ac_cv_lib_Xaw_main=no
ac_cv_lib_Xpm_main=no
ac_cv_lib_Xt_main=no
ac_cv_objext=o
ac_cv_path_EGREP='/usr/bin/grep -E'
ac_cv_path_GREP=/usr/bin/grep
ac_cv_path_install='/usr/local/bin/ginstall -c'
ac_cv_prog_AWK=nawk
ac_cv_prog_CPP='gcc -E'
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_make_make_set=yes
ac_cv_search_gethostbyname='none required'
ac_cv_search_socket='none required'
am_cv_CC_dependencies_compiler_type=gcc3

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/tnlab/s-okubo/home2/prog/daihu/server/automake3/missing --run aclocal-1.9'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='${SHELL} /home/tnlab/s-okubo/home2/prog/daihu/server/automake3/missing --run tar'
AUTOCONF='${SHELL} /home/tnlab/s-okubo/home2/prog/daihu/server/automake3/missing --run autoconf'
AUTOHEADER='${SHELL} /home/tnlab/s-okubo/home2/prog/daihu/server/automake3/missing --run autoheader'
AUTOMAKE='${SHELL} /home/tnlab/s-okubo/home2/prog/daihu/server/automake3/missing --run automake-1.9'
AWK='nawk'
CC='gcc'
CCDEPMODE='depmode=gcc3'
CFLAGS='-g -O2'
CPP='gcc -E'
CPPFLAGS=''
CYGPATH_W='echo'
DEFS='-DHAVE_CONFIG_H'
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/usr/bin/grep -E'
EXEEXT=''
GREP='/usr/bin/grep'
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='${SHELL} $(install_sh) -c -s'
LDFLAGS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /home/tnlab/s-okubo/home2/prog/daihu/server/automake3/missing --run makeinfo'
OBJEXT='o'
PACKAGE='server'
PACKAGE_BUGREPORT='tnlab-webmaster@ice.uec.ac.jp'
PACKAGE_NAME='server'
PACKAGE_STRING='server 0.2'
PACKAGE_TARNAME='server'
PACKAGE_VERSION='0.2'
PATH_SEPARATOR=':'
SET_MAKE=''
SHELL='/bin/bash'
STRIP=''
VERSION='0.2'
XMKMF=''
X_CFLAGS=' -I/usr/X11R6/include'
X_EXTRA_LIBS=''
X_LIBS=' -L/usr/X11R6/lib'
X_PRE_LIBS=' -lSM -lICE'
ac_ct_CC='gcc'
am__fastdepCC_FALSE='#'
am__fastdepCC_TRUE=''
am__include='include'
am__leading_dot='.'
am__quote=''
am__tar='${AMTAR} chof - "$$tardir"'
am__untar='${AMTAR} xf -'
bindir='${exec_prefix}/bin'
build_alias=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='${prefix}'
host_alias=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='/home/tnlab/s-okubo/home2/prog/daihu/server/automake3/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(install_sh) -d'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr/local'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

#define PACKAGE_NAME "server"
#define PACKAGE_TARNAME "server"
#define PACKAGE_VERSION "0.2"
#define PACKAGE_STRING "server 0.2"
#define PACKAGE_BUGREPORT "tnlab-webmaster@ice.uec.ac.jp"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_UNISTD_H 1
#define HAVE_BZERO 1
#define HAVE_INET_NTOA 1
#define HAVE_MEMSET 1
#define HAVE_SOCKET 1

configure: exit 0
